### ISSUE TITLE
Again: list-directory replaces [ characters in filenames with \\[, resulting in an extra backslash...

### ISSUE THREAD

**Issue by stacksmith** [edicl/cl-fad#16]
With all due respect, loading a directory containing a file with a "[" in its name creates a path containing a "\\\\[".  With two backslashes.  The first backslash escapes the second, resulting in a backslash before the brace.  The file cannot be opened because of the extra backslash.

For example, given a file "[xxx", list-directory presents it as #P"\\\\[xxx" in the path.  The resultant (wrong) filename is therefore "\\[xxx" instead of "[xxx".  

This is a bug that needs to be addressed - I'd hate to kludge a workaround searching for backslashes before an open brace.

Please do not close this issue without investigating it.  This is confusing because github does its own escaping, so I think that my previous issue was not understood correctly.

**Comment by hanshuebner** [comment]
cl-fad is a wrapper around the CL pathname system, and the CL pathname system is not able to deal with all possible file names that can occur.  It is a portability wrapper around different file systems, and it only works reliably for files that one creates using it.  Files with arbitrary path names created with other programs, or even with CL using non-portable characters in the name are causing portability problems, and cl-fad is not going to fix that.  If you need to deal with arbitrary file names, don't use CL pathnames for it.  One way to do this is by using [IOlib](https://common-lisp.net/project/iolib/).

If you have a fix for your problem in cl-fad, please submit a pull request.

**Comment by stacksmith** [comment]
As I understand it, the [ and ] characters are valid in all filesystems (see https://en.wikipedia.org/wiki/Filename  for example).  It is reasonable to expect cl-fad to handle valid characters in filenames.

I will see what I can do about fixing it, although I was hoping someone more qualified from the cl-fad team could do it better.

**Comment by hanshuebner** [comment]
Random Wikipedia pages are not a credible source to support your case.

When CL was created, different file systems were in common use and its pathname system is meant to support these.  VMS, for example, would use path names like `FOO$BAR::BAZ:[DIRECTORY.SUB-DIRECTORY]FILE-NAME.EXT;234` and Common Lisp would gladly support that.

**Comment by stacksmith** [comment]
And I thought correctness was something all Lisp programmers were concerned with.  

Sorry, Hans, I guess VMS pathnames should be supported, and Linux - not so much.

**Comment by stassats** [comment]
Well, the thing is, cl-fad is working without issues with [ in pathnames coming from list-directory. And nothing in cl-fad or SBCL has changed recently in that area to affect it. So you are either misinterpreting your findings or are not showing us your complete test cases.

**Comment by hanshuebner** [comment]
@stacksmith I'm personally not interested in making cl-fad support funny characters in file names, because it would be a never-ending effort and I don't have the need for it.  This has nothing to do with correctness, but with motivation.  It helps to understand the history of CL to understand why the pathname system has difficulties with file names that contain characters which are considered to be delimiters in other, maybe obsolete or ancient systems.  Your remark regarding "cl-fad"'s "inability" to correctly parse a VMS file name is besides the point, because you're not running on VMS.  If you were running cl-fad on a CL implementation on VMS and it would fail to support a native VMS path, you'd have a bug to report.

Stas seems to have a different take and motivation and have questions regarding what you reported as a bug, so I'm leaving it up to him to send any further responses.

**Comment by stacksmith** [comment]
stassats, thank you for your reply.  My software needs to handle filenames I have no control over, and on further investigation it appears that cl-fad is not at fault - .  Paths with double-backslash-open-brace can be opened inside Lisp.  However, they  **are not displayed correctly or passed as parameters to outside applications**.  I understand if you feel that it is not a problem of cl-fad.

Do you have any suggestions for a clean way of creating a correct visual representation of a path (allowing the user to spell it out and still find the file in the file manager, for instance) as well as a string representation that could be passed outside to the OS?

I'd hate to have to yank backslashes out of the pathstring for this one case - and who knows what other cases there are...

Thanks

**Comment by stassats** [comment]
Try uiop:native-namestring
