### ISSUE TITLE
The test compares truename with non-truenames

### ISSUE THREAD

**Issue by Yehouda** [edicl/cl-fad#32]
In fad.test.lisp, close to the bottom, it creates a list of namestrings and bind the variabe **list** to it , and then searches in this list using **find**. But it searches for namestrings of truenames, which may be different, for example if the pathname is a link. 
It causes the assertion to fail for "test 29". 
Can be fixed by calling truename on the paths thatgo in the list, for example changing line 148:
`  (list (mapcar #'namestring (list-directory fad-dir))))`
to
`(list (mapcar #'namestring (mapcar 'truename(list-directory fad-dir)))))`

**Comment by stassats** [comment]
But list-directory is advertised as returning truenames.

**Comment by Yehouda** [comment]
Ah, yes.
It is a bug in LispWorks.
