### ISSUE TITLE
Bug in PATHNAME-AS-DIRECTORY

### ISSUE THREAD

**Issue by Devon7** [edicl/cl-fad#35]
(pathname-directory (fad:pathname-as-directory "~")) => (:ABSOLUTE "Users" "devon" "")
but should be (:ABSOLUTE "Users" "devon")

**Comment by Devon7** [comment]
(list :software (list (software-type) (software-version))
      :implementation (list (lisp-implementation-type) (lisp-implementation-version))
      :machine (machine-type)) =>
(:SOFTWARE ("Darwin" "18.7.0")
 :IMPLEMENTATION ("Clozure Common Lisp" "Version 1.12.1 (v1.12.1) DarwinX8664")
 :MACHINE "x86_64")

**Comment by stassats** [comment]
I don't think ~ is defined, it's an implementation specific thing.

**Comment by Devon7** [comment]
No input, defined or not, legal or not, should produce illegal output such as a `""` directory component.
CL-FAD exists because **_everything_** to do with pathnames is implementation specific.
By widespread convention `~` is the user's home directory - follow the rule of least surprise.
`#+CCL (setq pathspec (pathname pathspec))` seems to fix it in CCL,
now it runs (fad:walk-directory "~" …) ok but that's no stress test.
CCL does
```
	(pathname-name "~") => "~"
	(pathname-name #P"~") => NIL
	(pathname-name (pathname "~")) => NIL

```
therefore
```
	(fad:directory-pathname-p "~") => NIL
	(fad:directory-pathname-p #P"~") => #P"/Users/devon/"
	(fad:directory-pathname-p (pathname "~")) => #P"/Users/devon/"
```
which smells buggy to me, I'll grovel their sources and maybe talk to them too.

**Comment by stassats** [comment]
fad is a portability layer, ~ is not portable, so how it works is moot.

**Comment by Devon7** [comment]
A portability layer that injects illegal time bombs such as this is not helpful to anyone.
