### ISSUE TITLE
On the bordeaux-threads dependency

### ISSUE THREAD

**Issue by yowipo1** [edicl/cl-fad#37]
When creating temporary files, it seems you guys depend on bordeaux-threads' `make-lock`.

```;; locking for multi-threaded operation with unsafe random function
(defvar *create-file-name-lock* (bordeaux-threads:make-lock "Temporary File Name Creation Lock"))

(defmacro with-file-name-lock-held (() &body body)
  `(bordeaux-threads:with-lock-held (*create-file-name-lock*)
     ,@body))
```
Source: temporary-files.lisp.

It turns out that `bordeaux-threads` [doesn't quickload](https://github.com/sionescu/bordeaux-threads/issues/126) on a Debian system with SBCL version 1.2.4.

```
%sbcl --version
SBCL 1.2.4.debian
```

So, effectively, we can't install `cl-fad` there either.  Isn't a dependency on bordeaux-threads a bit too much for a files and directories library?  I ended up replacing cl-fad with [pathname-utils](https://shinmera.github.io/pathname-utils/ ) and [filesystem-utils](https://quickref.common-lisp.net/filesystem-utils.html).

**Comment by stassats** [comment]
Not a cl-fad issue.

**Comment by hanshuebner** [comment]
> Isn't a dependency on bordeaux-threads a bit too much for a files and directories library? 

No.  bordeaux-threads is just a compatibility shim, not an actual library providing functionality on its own.  @sionescu is completely right, don't use an outdated SBCL and you're golden.
